version: "3.8"
services:
  backend-flask:
    environment:
      FRONTEND_URL: "*"
      BACKEND_URL: "*"
    build: ./backend-flask
    ports:
      - "4567:4567"
    healthcheck:
      test: curl http://localhost:4567/health
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    volumes:
      - ./backend-flask:/backend-flask

  frontend-react-js:
    environment:
      REACT_APP_BACKEND_URL: "http://localhost:4567"
    build: ./frontend-react-js
    ports:
      - "3000:3000"
    healthcheck:
      test: curl http://localhost:3000
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    volumes:
      - ./frontend-react-js:/frontend-react-js
      - /frontend-react-js/node_modules

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - PGUSER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    healthcheck:
      test: pg_isready
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    volumes:
      - db:/var/lib/postgresql/data

  dynamodb-local:
    # https://stackoverflow.com/questions/67533058/persist-local-dynamodb-data-in-volumes-lack-permission-unable-to-open-databa
    # We needed to add user:root to get this working.
    user: root
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - ./docker/dynamodb:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal

networks:
  default:
    name: cruddur

volumes:
  db:
    driver: local
